#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Please provide a tag."
	echo "Usage: ./release.sh v[X.Y.Z]"
	exit
fi

echo "Preparing $1..."

# Update the version
msg="# managed by release.sh"
sed -E -i "s/^version = .* ${msg}$/version = \"${1#v}\" ${msg}/" Cargo.toml
echo "${1#v}" > VERSION
cargo build

# Update the changelog
git cliff --config cliff.toml --tag "$1" >CHANGELOG.md
prettier -w CHANGELOG.md
