#!/usr/bin/env bash

export GIT_CLIFF_TEMPLATE="\
	{% for group, commits in commits | group_by(attribute=\"group\") %}
	{{ group | upper_first }}\
	{% for commit in commits %}
		- {% if commit.breaking %}(breaking) {% endif %}{{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end=\"\") }})\
	{% endfor %}
	{% endfor %}"
changelog=$(git cliff --config cliff.toml --unreleased --strip all)

git checkout main
git fetch -p && git pull
git tag -a "$1" -m "Release $1" -m "${changelog}" 

git push --tags
