name: Shellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: "-e SC2148"
